### ISSUE TITLE
The on-hover popup is cutoff when aligned above the flow element

### ISSUE THREAD

**Issue by PouriaSterling** [agiledigital/mule-preview#47]
As you can see in the image below, the popup that comes up when I hover on a newly added flow gets cutoff when it has to align itself at the top (i.e. when the flow is at the bottom of the screen and the popup has no room to appear below the flow).
![62672362-b9f0fc80-b9dd-11e9-8ffa-43657deb74da](https://user-images.githubusercontent.com/2357137/62746334-43fa9d00-ba92-11e9-95b6-426fa7256c82.png)

**Comment by NoxHarmonium** [comment]
I'm using https://re-com.day8.com.au/#/popovers to render the popovers, this might be a bug with that plugin. In that case I might have to write custom popovers. I will need to investigate further.
