### ISSUE TITLE
Branch Diff does not work

### ISSUE THREAD

**Issue by haolinj** [agiledigital/mule-preview#48]
When you view a branch diffs on Bitbucket, the preview does not open. 

Inspected console, you get `t is not defined` error on `diff.js` line 20 (https://github.com/agiledigital/mule-preview/blob/master/browser-plugin/src/app/modes/diff.js#L20) and `console.error` logged at line 31. 

Works on PR diffs and source view. 

(This is on Firefox)

**Comment by NoxHarmonium** [comment]
For the PR view, we can get diff information by just taking the current URL and making a request to it with the `accept` header set to `application/json` and diff information is returned.
The branch diff is more complicated, it calls a specific REST API endpoint so I'd have to work out how that is constructed to fix this issue.

**Comment by NoxHarmonium** [comment]
The REST API call that the diff page makes looks like this `https://bitbucket.com/rest/api/latest/projects/FP/repos/sample-mule-project/compare/changes?from=42d1b74fad8af18ee0d88256c4f9dd218dc9c526&fromRepo=761&to=06fbb70f52044f963ca30dcdbd1eb9bc9ccd1a8f&start=0&limit=1000`

You can access the page state using Bitbucket Javascript functions which would help construct this URL.

```
> require('bitbucket/internal/model/page-state')
Object { extend: extend(), getCurrentUser: r(), setCurrentUser: t(), getProject: r(), setProject: t(), getRepository: r(), setRepository: t(), getPullRequest: r(), setPullRequest: t(), getBranch: r(), … }
```
We can use this on Firefox using [wrappedJSObject](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/wrappedJSObject) but it gets more complicated on Chrome, we need to inject script tags into the page that sends a message back to the parent extension.
